version: "3.9"

services:

  nginx:
    image: nginx:1.23
    container_name: check_certificates-nginx-1.23
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - "./docker/tmp:/tmp"
      - "./docker/etc/nginx:/etc/nginx"
      - "./docker/var/log/nginx:/var/log/nginx"
      - "./docker/usr/share/nginx/html:/usr/share/nginx/html"
      - "./docker/usr/share/nginx/htdocs:/usr/share/nginx/htdocs"

  check_certificates:
    image: ghcr.io/pavelkim/check_certificates/check_certificates:1.7.2dev
    container_name: check_certificates-daemon
    environment:
      CHECK_INTERVAL: 7200
    volumes:
      - "./docker/etc/check_certificates:/etc/check_certificates"
      - "./docker/usr/share/nginx/htdocs:/htdocs"
    command:
      - "-i"
      - "/etc/check_certificates/domains.txt"
      - "-G"
    depends_on:
      - nginx
