name: Pull request to master

on:
  pull_request:
    branches: [ master ]

jobs:


  validate_new_version:
    name: Validate new version
    runs-on: ubuntu-latest
    outputs:
      planned_version: ${{ steps.validate_new_version.outputs.planned_version }}
      version_file_exists: ${{ steps.validate_new_version.outputs.version_file_exists }}
      tag_hash: ${{ steps.validate_new_version.outputs.tag_hash }}
      can_create: ${{ steps.validate_new_version.outputs.can_create }}
      tag_exists: ${{ steps.validate_new_version.outputs.tag_exists }}
      branch_name: ${{ steps.validate_new_version.outputs.branch_name }}

    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Use latest released action
        id: validate_new_version
        uses: reinvented-stuff/validate-version-action@1.2.0
        with:
          version_filename: ".version"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          fail_on_error: true


  build:
    name: Build dev branch
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Test run
      run: |
        export PROMETHEUS_EXPORT_FILENAME="./metrics"
        bash check_certificates.sh -G -i test/inputfile.txt --only-alerting --alert-limit 5 | tee test_run_result.txt

    - name: Test run results verification
      run: diff -u test_run_result.txt test/expected_result.txt

    - name: Test run results verification (metrics)
      run: cat ./metrics

    - name: Prepare shellspec directory
      id: shellspec_directory
      shell: bash
      run: |
        TMP_DIR=$(mktemp -d)
        echo "shellspec_directory=${TMP_DIR}" >> "${GITHUB_OUTPUT}"

    - name: Install shellspec
      id: shellspec_install
      shell: bash
      run: |
        curl -fsSL -o "${{ steps.shellspec_directory.outputs.shellspec_directory }}/shellspec" https://git.io/shellspec
        bash "${{ steps.shellspec_directory.outputs.shellspec_directory }}/shellspec" --prefix "${{ steps.shellspec_directory.outputs.shellspec_directory }}" -y

    - name: Run shellspec tests
      id: shellspec_run
      working-directory: ./test
      env:
        TZ: CET
      shell: bash
      run: |
        bash "${{ steps.shellspec_directory.outputs.shellspec_directory }}/bin/shellspec" -f d


